HealthcareProject/Models/MonthlyReport.cs
using System;
using System.Collections.Generic;

namespace HealthcareProject.Models
{
    public partial class MonthlyReport
    {
        public string ReportId { get; set; }
        public DateTime ReportMonth { get; set; }
        public int NoPatients { get; set; }
        public string DoctorName { get; set; }
        public double MonthlyIncome { get; set; }
    }
}

HealthcareProject/Controllers/MonthlyReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HealthcareProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Rotativa.AspNetCore;

namespace HealthcareProject.Controllers
{
    [Authorize(Roles = "CEO")]
    public class MonthlyReportsController : Controller
    {
        private readonly healthcarev1Context _context;

        public MonthlyReportsController(healthcarev1Context context)
        {
            _context = context;
        }
        
       /* // GET: MonthlyReports
        public async Task<IActionResult> Index(DateTime search_date)
        {
            if (!String.IsNullOrEmpty(search_date.ToShortDateString()))
            {
                var searchContext = _context.MonthlyReport.Where(c => c.ReportMonth.Date==search_date);
                return View(await searchContext.ToListAsync());
            }
            return View(await _context.MonthlyReport.ToListAsync());
        }*/


        // GET: MonthlyReports/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MonthlyReports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormCollection collection)
        {
            var Date = (DateTime.Parse(collection.ToArray()[0].Value).ToShortDateString().Split("/"))[0];

            if (ModelState.IsValid)
            {
                var monthlyReports = _context.MonthlyReport.AsEnumerable().Where(rec => (rec.ReportMonth.ToShortDateString().Split("/"))[0] == Date).ToList();
                return new ViewAsPdf("View", monthlyReports);
            }
            return NotFound();
        }


        /*// GET: MonthlyReports/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var monthlyReport = await _context.MonthlyReport
                .FirstOrDefaultAsync(m => m.ReportId == id);
            if (monthlyReport == null)
            {
                return NotFound();
            }

            return View(monthlyReport);
        }

        // GET: MonthlyReports/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MonthlyReports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReportId,ReportMonth,NoPatients,DoctorName,MonthlyIncome")] MonthlyReport monthlyReport)
        {
            if (ModelState.IsValid)
            {
                _context.Add(monthlyReport);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(monthlyReport);
        }

        // GET: MonthlyReports/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var monthlyReport = await _context.MonthlyReport.FindAsync(id);
            if (monthlyReport == null)
            {
                return NotFound();
            }
            return View(monthlyReport);
        }

        // POST: MonthlyReports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ReportId,ReportMonth,NoPatients,DoctorName,MonthlyIncome")] MonthlyReport monthlyReport)
        {
            if (id != monthlyReport.ReportId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(monthlyReport);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MonthlyReportExists(monthlyReport.ReportId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(monthlyReport);
        }

        // GET: MonthlyReports/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var monthlyReport = await _context.MonthlyReport
                .FirstOrDefaultAsync(m => m.ReportId == id);
            if (monthlyReport == null)
            {
                return NotFound();
            }

            return View(monthlyReport);
        }

        // POST: MonthlyReports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var monthlyReport = await _context.MonthlyReport.FindAsync(id);
            _context.MonthlyReport.Remove(monthlyReport);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MonthlyReportExists(string id)
        {
            return _context.MonthlyReport.Any(e => e.ReportId == id);
        }*/
    }
}

HealthcareProject/Views/MonthlyReports/Create.cshtml
@model HealthcareProject.Models.MonthlyReport

@{
    ViewData["Title"] = "Create";
}


<h4>MonthlyReport</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <p> Select Date</p>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="ReportMonth" class="control-label"></label>
                <input asp-for="ReportMonth" class="form-control" type="date" />
                <span asp-validation-for="ReportMonth" class="text-danger"></span>
            </div>


            <input type="submit" value="Get Monthly Report" class="btn btn-primary" />



        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HealthcareProject/Views/MonthlyReports/Delete.cshtml
@model HealthcareProject.Models.MonthlyReport

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MonthlyReport</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReportMonth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReportMonth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoPatients)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoPatients)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoctorName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoctorName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MonthlyIncome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MonthlyIncome)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ReportId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HealthcareProject/Views/MonthlyReports/Details.cshtml
@model HealthcareProject.Models.MonthlyReport

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MonthlyReport</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReportMonth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReportMonth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoPatients)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoPatients)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoctorName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoctorName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MonthlyIncome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MonthlyIncome)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ReportId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HealthcareProject/Views/MonthlyReports/Edit.cshtml
@model HealthcareProject.Models.MonthlyReport

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MonthlyReport</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ReportId" />
            <div class="form-group">
                <label asp-for="ReportMonth" class="control-label"></label>
                <input asp-for="ReportMonth" class="form-control" />
                <span asp-validation-for="ReportMonth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoPatients" class="control-label"></label>
                <input asp-for="NoPatients" class="form-control" />
                <span asp-validation-for="NoPatients" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoctorName" class="control-label"></label>
                <input asp-for="DoctorName" class="form-control" />
                <span asp-validation-for="DoctorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MonthlyIncome" class="control-label"></label>
                <input asp-for="MonthlyIncome" class="form-control" />
                <span asp-validation-for="MonthlyIncome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

HealthcareProject/Views/MonthlyReports/Index.cshtml
@model IEnumerable<HealthcareProject.Models.MonthlyReport>

@{
    ViewData["Title"] = "Monthly Reports";
}

<h1>Monthly Reports</h1>

<form asp-controller="MonthlyReports" asp-action="Index" method="get">
    <p>Please enter last day of the month fo the monthly report!</p>
    <p>
        <input type="date" name="SearchDate">
        <input type="submit" value="Find Monthly Report" />
    </p>
</form>

@if (Model.Count() == 0)
{
    <p> We cannot find any report for the selected date!</p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ReportMonth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoPatients)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoctorName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MonthlyIncome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ReportMonth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoPatients)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoctorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MonthlyIncome)
            </td>
          
        </tr>
}
    </tbody>
</table>

HealthcareProject/Views/MonthlyReports/View.cshtml
@model IEnumerable<HealthcareProject.Models.MonthlyReport>


<h1>Monthly Report Summary</h1>


<table class="table">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.DoctorName)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.ReportMonth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoPatients)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.MonthlyIncome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.DoctorName)
            </td>
            <td>
               @item.ReportMonth.Date.ToLongDateString();
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoPatients)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.MonthlyIncome)
            </td>


        </tr>
        }
    </tbody>
</table>