HealthcareProject/Models/DailyReport.cs
using System;
using System.Collections.Generic;

namespace HealthcareProject.Models
{
    public partial class DailyReport
    {
        public DateTime ReportDate { get; set; }
        public int NoPatients { get; set; }
        public string ReportId { get; set; }
        public string DoctorName { get; set; }
        public double DailyIncome { get; set; }
    }
}

HealthcareProject/Controllers/DailyReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HealthcareProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Rotativa.AspNetCore;

namespace HealthcareProject.Controllers
{
    [Authorize(Roles = "CEO")]
    public class DailyReportsController : Controller
    {
        private readonly healthcarev1Context _context;

        public DailyReportsController(healthcarev1Context context)
        {
            _context = context;
        }
        //For Report Generation
        public class Report
        {
            public DateTime ReportDate;

            public string DoctorEmail;

        } // GET: DailyReports/Create
        public IActionResult Create()
        {

            IEnumerable<SelectListItem> Doctors = _context.Doctor.Select(doc => new SelectListItem
            {
                Value = doc.DoctorEmail,
                Text = doc.DoctorEmail
            });
            ViewBag.DoctorEmail = Doctors;

            return View();
        }

        // POST: DailyReports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormCollection collection)
        {

            var Date = DateTime.Parse(collection.ToArray()[0].Value).ToShortDateString();

            if (ModelState.IsValid)
            {

                var reportContext = _context.DailyReport.AsEnumerable().Where(rec => rec.ReportDate.ToShortDateString() == Date).ToList();

                return new ViewAsPdf("View",  reportContext);
            }
            return NotFound();
        }

        /*// GET: DailyReports/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DailyReports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReportDate,NoPatients,ReportId,DoctorName,DailyIncome")] DailyReport dailyReport)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dailyReport);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dailyReport);
        }

        // GET: DailyReports/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dailyReport = await _context.DailyReport.FindAsync(id);
            if (dailyReport == null)
            {
                return NotFound();
            }
            return View(dailyReport);
        }

        // POST: DailyReports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ReportDate,NoPatients,ReportId,DoctorName,DailyIncome")] DailyReport dailyReport)
        {
            if (id != dailyReport.ReportId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dailyReport);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DailyReportExists(dailyReport.ReportId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dailyReport);
        }

        // GET: DailyReports/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dailyReport = await _context.DailyReport
                .FirstOrDefaultAsync(m => m.ReportId == id);
            if (dailyReport == null)
            {
                return NotFound();
            }

            return View(dailyReport);
        }

        // POST: DailyReports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var dailyReport = await _context.DailyReport.FindAsync(id);
            _context.DailyReport.Remove(dailyReport);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DailyReportExists(string id)
        {
            return _context.DailyReport.Any(e => e.ReportId == id);
        }*/
    }
}

HealthcareProject/Views/DailyReports/Create.cshtml
@model HealthcareProject.Controllers.DailyReportsController.Report

@{
    ViewData["Title"] = "Get Report";
}



<h4>Report</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <p> Select Date</p>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">

                <div class="form-group">
                    <label asp-for="ReportDate" class="control-label"></label>
                    <input asp-for="ReportDate" class="form-control" type="date"/>
                    <span asp-validation-for="ReportDate" class="text-danger"></span>
                </div>


                <input type="submit" value="Get Daily Report" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HealthcareProject/Views/DailyReports/Delete.cshtml
@model HealthcareProject.Models.DailyReport

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DailyReport</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReportDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReportDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoPatients)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoPatients)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoctorName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoctorName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DailyIncome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DailyIncome)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ReportId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HealthcareProject/Views/DailyReports/Details.cshtml
@model HealthcareProject.Models.DailyReport

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>DailyReport</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReportDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReportDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoPatients)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoPatients)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoctorName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoctorName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DailyIncome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DailyIncome)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ReportId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HealthcareProject/Views/DailyReports/Edit.cshtml
@model HealthcareProject.Models.DailyReport

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DailyReport</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ReportDate" class="control-label"></label>
                <input asp-for="ReportDate" class="form-control" />
                <span asp-validation-for="ReportDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoPatients" class="control-label"></label>
                <input asp-for="NoPatients" class="form-control" />
                <span asp-validation-for="NoPatients" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="ReportId" />
            <div class="form-group">
                <label asp-for="DoctorName" class="control-label"></label>
                <input asp-for="DoctorName" class="form-control" />
                <span asp-validation-for="DoctorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DailyIncome" class="control-label"></label>
                <input asp-for="DailyIncome" class="form-control" />
                <span asp-validation-for="DailyIncome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HealthcareProject/Views/DailyReports/Index.cshtml
@model IEnumerable<HealthcareProject.Models.DailyReport>

@{
    ViewData["Title"] = "Daily Report";
}

<h1>Daily Reports</h1>
<form asp-controller="DailyReports" asp-action="Index" method="get">
    <p>Please enter Please enter the date you want the record of!</p>
    <p>
        <input type="date" name="SearchDate">
        <input type="submit" value="Find Monthly Report" />
    </p>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ReportDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoPatients)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoctorName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DailyIncome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ReportDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoPatients)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoctorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DailyIncome)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ReportId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ReportId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ReportId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

HealthcareProject/Views/DailyReports/View.cshtml
@model IEnumerable<HealthcareProject.Models.DailyReport>


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Patient Appointments Page</title>
    <link rel="stylesheet" href="~/BootStrap Views Assets - Do Not Touch/Appointments/Index/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/BootStrap Views Assets - Do Not Touch/Appointments/Index/assets/fonts/font-awesome.min.css">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

    <link rel="stylesheet" href="~/BootStrap Views Assets - Do Not Touch/Appointments/Index/assets/css/styles.min.css">

</head>

<body>
    <section>
        <div class="row">
            <div class="col">
                <p style="font-size: 30px;filter: brightness(138%);background-color: #676161;">Daily Report Summary</p>
            </div>
        </div>
        <div class="row" id="appointments">
            <!-- Start: Table With Search -->


            <div class="table-responsive table-bordered table table-hover table-bordered results">
                <table class="table table-bordered table-hover">
                    <thead class="border rounded-0 bill-header cs">

                        <tr>
                            <th id="trs-hd" class="col-lg-1"> Count</th>
                            <th id="trs-hd" class="col-lg-2">Doctor Name</th>
                            <th id="trs-hd" class="col-lg-2">No. of Patients</th>
                            <th id="trs-hd" class="col-lg-2">Daily Income</th>

                        </tr>

                    </thead>
                    <tbody>
                        @{ int count = 1;}
                        @foreach (var record in Model)
                        {
                            <tr>
                                <td>@count</td>
                                <td>@Html.DisplayFor(entry => record.DoctorName)</td>
                                <td>@Html.DisplayFor(entry => record.NoPatients)</td>
                                <td>@Html.DisplayFor(entry => record.DailyIncome)</td>
                                <td>
                                </td>
                            </tr>
                            count = count + 1;
                        }
                    </tbody>
                </table>
            </div>


        </div>
    </section>
    <script src="~/BootStrap Views Assets - Do Not Touch/Appointments/Index/assets/js/jquery.min.js"></script>
    <script src="~/BootStrap Views Assets - Do Not Touch/Appointments/Index/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/BootStrap Views Assets - Do Not Touch/Appointments/Index/assets/js/script.min.js"></script>
</body>
</table>