HealthcareProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HealthcareProject.Models;

namespace HealthcareProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HealthcareProject/Controllers/NursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HealthcareProject.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace HealthcareProject.Controllers
{
    [Authorize(Roles = "CEO")]
    public class NursesController : Controller
    {
        private readonly healthcarev1Context _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signManager;

        public NursesController(healthcarev1Context context, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signManager)
        {
            _context = context;
            _userManager = userManager;
            _signManager = signManager;
        }

        // GET: Nurses
        public async Task<IActionResult> Index()
        {
            var healthcarev1Context = _context.Nurse.Include(n => n.Doctor);
            return View(await healthcarev1Context.ToListAsync());
        }

        // GET: Nurses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nurse = await _context.Nurse
                .Include(n => n.Doctor)
                .FirstOrDefaultAsync(m => m.NurseId == id);
            if (nurse == null)
            {
                return NotFound();
            }

            return View(nurse);
        }

        // GET: Nurses/Create
        public IActionResult Create()
        {
            ViewData["DoctorId"] = new SelectList(_context.Doctor, "DoctorId", "DoctorEmail");
            return View();
        }

        // POST: Nurses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NurseName,Salary,NurseEmail,NurseId,DoctorId")] Nurse nurse)
        {
            if (ModelState.IsValid)
            {
                _context.Add(nurse);
                await _context.SaveChangesAsync();
                
                // Create nurse account using the email and default password

                var nurseaccount = new IdentityUser
                {
                    UserName = nurse.NurseEmail,
                    Email = nurse.NurseEmail,
                    EmailConfirmed = true,


                };

                var user = await _userManager.FindByEmailAsync(nurse.NurseEmail);
                if (user == null)
                {
                    var createpoweruser = await _userManager.CreateAsync(nurseaccount, "Superuser1!");
                    if (createpoweruser.Succeeded)
                    {
                        await _userManager.AddToRoleAsync(nurseaccount, "Nurse");
                    }

                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DoctorId"] = new SelectList(_context.Doctor, "DoctorId", "DoctorEmail", nurse.DoctorId);
            return View(nurse);
        }

        // GET: Nurses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nurse = await _context.Nurse.FindAsync(id);
            if (nurse == null)
            {
                return NotFound();
            }
            ViewData["DoctorId"] = new SelectList(_context.Doctor, "DoctorId", "DoctorEmail", nurse.DoctorId);
            return View(nurse);
        }

        // POST: Nurses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NurseName,Salary,NurseEmail,NurseId,DoctorId")] Nurse nurse)
        {
            if (id != nurse.NurseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nurse);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NurseExists(nurse.NurseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DoctorId"] = new SelectList(_context.Doctor, "DoctorId", "DoctorEmail", nurse.DoctorId);
            return View(nurse);
        }

        // GET: Nurses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nurse = await _context.Nurse
                .Include(n => n.Doctor)
                .FirstOrDefaultAsync(m => m.NurseId == id);
            if (nurse == null)
            {
                return NotFound();
            }

            return View(nurse);
        }

        // POST: Nurses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var nurse = await _context.Nurse.FindAsync(id);
            _context.Nurse.Remove(nurse);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NurseExists(int id)
        {
            return _context.Nurse.Any(e => e.NurseId == id);
        }
    }
}

HealthcareProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<link rel="stylesheet" href="~/css//StyleSheet.css" />
<head>


</head>
@if (!User.Identity.IsAuthenticated)
{
    <body background="/healthcare.jpeg" background-repeat: no-repeat background-size: cover>
        <div class="text-center">
            <h1 class="display-4">Welcome to Healthcare Service!</h1>

            <p><a href="https://www.qfxsoftware.com/download.htm">KeyScrambler! Please install to make your usage secure.</a></p>

        </div>
    </body>
}
@if (User.Identity.IsAuthenticated && User.IsInRole("CEO"))
{
    <body background="/healthcare.jpeg" background-repeat: no-repeat background-size: cover>
        <div class="sidenav">
            <a asp-controller="DailyReports" asp-action="Create">Daily Reports</a>
            <a asp-controller="MonthlyReports" , asp-action="Create">Monthly Reports</a>
            <a asp-controller="Doctors" asp-action="Index">Change Doctor Salary</a>
            <a asp-controller="Nurses" asp-action="Index">Change Nurse Salary</a>
            <a asp-controller="Patients" asp-action="Index">Patients</a>
            <a asp-controller="CardPayments" asp-action="Index">Card Payments</a>
            <a asp-controller="CashPayments" asp-action="Index">Cash Payments</a>
            <a asp-controller="CheckPayments" asp-action="Index">Check Payments</a>
         
        </div>
    </body>

}

@*
    @if (User.Identity.IsAuthenticated && User.IsInRole("Doctor"))
    {
        <body>
            <div class="sidenav">
                <a asp-controller="VisitRecords" asp-action="Index">Visit Records</a>
                <a asp-controller="Appointments1" asp-action="Index">My Appointments</a>
            </div>
        </body>
    }
*@

@if (User.Identity.IsAuthenticated && User.IsInRole("Nurse"))
{
    <body background="/healthcare.jpeg" background-repeat: no-repeat background-size: cover>
        <div class="sidenav">
            <a asp-controller="VisitRecords" asp-action="Index">My Appointments</a>


        </div>
    </body>
}


@if (User.Identity.IsAuthenticated && User.IsInRole("Patient"))
{
    <body background="/healthcare.jpeg" background-repeat: no-repeat background-size: cover>
        <div class="sidenav">
            <a asp-controller="Appointments1" asp-action="Index">Appointment</a>
            <a asp-controller="Billings" asp-action="Index">Invoice/Payment</a>
            <a asp-controller="MedicalReports" asp-action="Index">Medical Reports</a>
            <a asp-controller="Patients" asp-action="Index">Personal and Medical Info</a>
            <a asp-controller="VisitRecords" asp-action="Index">Hospital Visit Records</a>

        </div>
    </body>
}

@if (User.Identity.IsAuthenticated && User.IsInRole("Staff"))
{

    <body background="/healthcare.jpeg" background-repeat: no-repeat background-size: cover>
        <div class="sidenav">
            <a asp-controller="Appointments1" asp-action="Index">Appointments</a>
            <a asp-controller="Billings" asp-action="Index">Invoices</a>
            <a asp-controller="DoctorUnavailabilities" asp-action="Index">Add Doctor Unavailibility</a>
            <a asp-controller="DoctorAvailabilities" asp-action="Index">Add Doctor Availibility</a>
            <a asp-controller="Patients" asp-action="Index">Patients</a>
            <a asp-controller="MedicalReports" asp-action="Index">Add Medical Reports</a>
        </div>
    </body>

}
@if (User.Identity.IsAuthenticated && User.IsInRole("Doctor"))
{
    <body background="/healthcare.jpeg" background-repeat: no-repeat background-size: cover>

        <div class="sidenav">
            <div class="grid-item"> <a asp-area="" asp-controller="VisitRecords" asp-action="Index">My Appointments</a></div>


        </div>


    </body>
}